# Generated by Django 3.1.7 on 2021-03-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numb', models.CharField(max_length=30, verbose_name='订单编号')),
                ('order_receiving_time', models.DateField(verbose_name='接单时间')),
                ('order_time', models.DateField(verbose_name='采购时间')),
                ('purchaser', models.CharField(max_length=30, verbose_name='采购商')),
                ('product_numb', models.CharField(max_length=30, verbose_name='商品编号')),
                ('product', models.CharField(max_length=30, verbose_name='杂志名称')),
                ('Subscription_cycle', models.CharField(max_length=30, verbose_name='订阅周期')),
                ('customer_name', models.CharField(max_length=30, verbose_name='客户名称')),
                ('customer_tel', models.CharField(max_length=30, verbose_name='客户电话')),
                ('customer_add', models.CharField(max_length=100, verbose_name='客户地址')),
                ('distributor', models.CharField(max_length=30, verbose_name='分销商')),
                ('gift', models.CharField(max_length=30, verbose_name='赠品')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('attention', models.CharField(max_length=100, verbose_name='提示信息')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_tel', models.CharField(max_length=30, verbose_name='客户电话')),
                ('express_comp', models.CharField(max_length=30, verbose_name='快递公司')),
                ('deliverly_time', models.DateTimeField(verbose_name='发货时间')),
                ('tracking_numb', models.CharField(max_length=30, verbose_name='快递单号')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('magorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.magorder', verbose_name='订单编号')),
            ],
        ),
    ]
