# Generated by Django 3.1.7 on 2021-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magorder',
            name='gift',
        ),
        migrations.AddField(
            model_name='tracking',
            name='Subscription_cycle',
            field=models.CharField(max_length=30, null=True, verbose_name='订阅周期'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='deliverly_detail',
            field=models.CharField(max_length=100, null=True, verbose_name='发货明细'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='product',
            field=models.CharField(max_length=30, null=True, verbose_name='杂志名称'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
    ]
