# Generated by Django 3.1.7 on 2021-03-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210328_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magorder',
            name='Subscription_cycle',
            field=models.CharField(max_length=30, null=True, verbose_name='订阅周期'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='attention',
            field=models.CharField(max_length=100, null=True, verbose_name='提示信息'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='customer_add',
            field=models.CharField(max_length=100, null=True, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='customer_name',
            field=models.CharField(max_length=30, null=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='customer_tel',
            field=models.CharField(max_length=30, null=True, verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='distributor',
            field=models.CharField(max_length=30, null=True, verbose_name='分销商'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='order_numb',
            field=models.CharField(max_length=30, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='order_receiving_time',
            field=models.DateField(null=True, verbose_name='接单时间'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='order_time',
            field=models.DateField(null=True, verbose_name='采购时间'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='product',
            field=models.CharField(max_length=30, null=True, verbose_name='杂志名称'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='product_numb',
            field=models.CharField(max_length=30, null=True, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='purchaser',
            field=models.CharField(max_length=30, null=True, verbose_name='采购商'),
        ),
        migrations.AlterField(
            model_name='magorder',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='customer_tel',
            field=models.CharField(max_length=30, null=True, verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='deliverly_time',
            field=models.DateTimeField(null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='express_comp',
            field=models.CharField(max_length=30, null=True, verbose_name='快递公司'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='magorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='tracking.magorder', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_numb',
            field=models.CharField(max_length=30, null=True, verbose_name='快递单号'),
        ),
    ]
